server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    username: postgres
    password: ${ LOCAL_DB_PASSWORD }
    url: jdbc:postgresql://localhost:5432/ums
  jpa:
    hibernate:
      ddl-auto: update